namespace MuxSwarm.Utils;

public struct Help
{
    public static readonly string HelpText = string.Join("\r\n",
        "Mux-Swarm — A Configurable, CLI-First Agent Swarm Runtime & Operating Environment",
        "",
        "Slash Commands",
        "  /swarm          Launch interactive multi agent swarm loop",
        "  /pswarm         Launch parallel swarm - concurrent batch dispatch for independent tasks",
        "  /agent          Launch interactive single agent loop",
        "  /onboard        Create or update your operator profile (BRAIN.md + MEMORY.md)",
        "  /stateless      Stateless single agent loop, ideal for one-off tasks",
        "  /subagents      (/sub shorthand) Enable sub-agent delegation in standard single agent loop for one-off specialist tasks",
        "  /parasubagents  (/psub shorthand) Enable parallel sub-agent delegation in standard single agent loop for one-off specialist tasks",
        "  /addcontext     Allows configuration of what context each agent is injected with (supports custom overrides)",
        "  /plan           Toggle plan mode, agents present a plan and ask for approval before executing",
        "  /ultra          Toggle deep-reasoning mode (plan + maximum reasoning budget + heavy delegation)",
        "  /giga           Toggle giga mode (ultra + the agent can spawn teams and author/run workflows itself)",
        "  /classic        Switch to the classic line-by-line renderer (opt out of the live TUI)",
        "  /tui            Switch to the live full-screen TUI renderer (capable terminals only)",
        "  /verbose        Toggle TUI tool output between compact (collapsed) and full panels",
        "  /subagentview   (/sav) Toggle delegated sub-agent output between collapsed (one expandable line) and inline streaming",
        "  /continuous     Toggles continued autonomous execution on and off (shorthand /cont)",
        "  /workflow       <file> Run deterministic and replayable workflows with control of the entire mux-swarm runtime",
        "  /teams          List configured teams, or launch one: /teams <name> (members stream into Agent View; Ctrl+T toggles the TaskBoard strip)",
        "  /createteam      Guided wizard to create a team (name, lead, members, coordination, maxParallel) and save it to swarm.json teams[]",
        "  /kanban          (in a taskboard team) editable board: add/assign/move/ready/remove tasks + toggle peer self-claim (/kanban help)",
        "  /resume         Resume a previous single-agent session (swarm uses memory layers for continuity)",
        "  /tag            (in-session) Tag the live session with free-form text for easy resume/search; optional MEMORY.md stub",
        "  /compact        Compact current session context now (optional steering: /compact <instruction>)",
        "  /handoff        Write a resume-from-cold handoff doc (active model) to the sandbox reports dir [/handoff <msg|path.md>]",
        "  /heal, /reflect Review the session + propose BRAIN/MEMORY self-heal entries to approve [/heal deep] [steering]",
        "  /fix            Diagnose + repair a misbehaving Mux subsystem (config, MCP, proxy, skills, sandbox) [/fix <what is wrong>]",
        "  /diff           Show the working-tree git diff (collapsible)",
        "  /doctor         Health check: providers, MCP servers, sandbox, proxy (no model call)",
        "  /cost           Session token usage + estimated cost ($ for API providers; usage-only for subscriptions)",
        "  /init           Analyze the workspace and scaffold a project context file (AGENTS.md)",
        "  /review         AI review of the working-tree diff (read-only findings)",
        "  !<command>      Run a shell command and add its output to the conversation context",
        "  /tokens         Show the current token / context breakdown for the session",
        "  /effort         Cycle the live reasoning-effort tier (also Shift+Tab)",
        "  /undo           Drop the last exchange from the session history",
        "  /retry          Re-run the last turn",
        "  /wipe           Clear the session history (keep the session)",
        "  /detach         Park the live session to the background (re-enter with /attach)",
        "  /attach         Re-enter a session parked via /detach [/attach <id>; bare = pick from list]",
        "  /background, /bg Manage detached background jobs",
        "  /maxp           Maximum number of agents that can be running in parallel. (Default 4)",
        "  /model          View current models set for your swarm",
        "  /setmodel       Change the model for any agent, orchestrator, or compaction agent in your swarm config",
        "  /swap           Swap the active agent for single-agent mode",
        "  /newagent       Guided wizard to create a swarm agent (name, MCP servers, model, prompt via helper agent or template)",
        "  /editagent      Edit a swarm agent (model, description, MCP servers, delegation) [/editagent <name>]",
        "  /delagent       Remove a swarm agent from Swarm.json (and optionally its prompt file) [/delagent <name>]",
        "  /config         Show ALL configuration settings (console, ultra, serve, docker) - every key is /set-editable",
        "  /set            Edit any config key: /set <key> <value> (e.g. /set ultra.thinkingBudget 20000). Bare /set opens a picker",
        "  /showreasoning  Show or hide streamed reasoning text: full|summary (shown, grey italic) or none (hidden). Persists to config",
        "  /provider       View or switch the active LLM provider",
        "  /login          Log in to a subscription provider (claude|codex|kimi|...) via the local CLIProxyAPI sidecar",
        "  /ping           Test the CLIProxyAPI sidecar + show per-provider login readiness",
        "  /proxy          Manage the CLIProxyAPI sidecar: /proxy status | /proxy update",
        "  /workspace      Show or set the @-file workspace root: /workspace <path> (re-indexes the @ picker)",
        "  /limits         Display current execution limits for orchestration and agents",
        "  /tools          List available MCP tools across enabled servers",
        "  /skills         List available local skills",
        "  /memory         View knowledge graph",
        "  /sessions       List all saved sessions with type and agent count",
        "  /dockerexec     Toggle Docker execution mode",
            "  /sandbox        Show/swap exec sandbox backend (host|docker|podman|gvisor|kata|bwrap|...)",
        "  /delimiter      Toggle multi-line input delimiter",
        "  /dbg            Enable tool call output (applies to stdio mode only)",
        "  /nodbg          Disable tool call output (applies to stdio mode only)",
        "  /setup          Run initial setup / reconfigure",
        "  /reloadskills   Refresh skills directory for any mid process changes",
        "  /installskill   Install a skill by name (openai/skills, VoltAgent/...) or from a GitHub repo URL",
        "  /refresh        Perform a full Mux system refresh by refreshing config, re-initializing MCP servers and re-loading skills",
        "  /report         Generate full session audit reports, tool calls, delegations, artifacts, and outcomes",
        "  /report <id>    Audit a specific session by timestamp",
        "  /clear          Clear screen",
        "  /status         View current system status: provider, models, tools, skills, and sessions",
        "  /shortcuts      Show keyboard shortcuts (alias /keys)",
        "  /exit           Exit Mux-Swarm",
        "",
        "Input & Editing (live TUI)",
        "  Enter           Submit the current message",
        "  Alt+Enter       Insert a newline (multi-line compose) without submitting",
        "  Ctrl+J          Insert a newline (alias for Alt+Enter on terminals that can\u2019t signal it)",
        "  /delimiter      Alternative multi-line mode: type a delimiter line to send a pasted block",
        "  Esc             Empty prompt: open transcript view; with text: enter vim Normal mode",
        "  Ctrl+E          Expand the most recent large/collapsed tool result in place",
        "  Ctrl+G          Open the transcript/expand view (secondary to Esc; never cancels the turn)",
        "  Ctrl+L          Clear resize/redraw artifacts and repaint (never cancels the turn)",
        "  Ctrl+R          Reverse-search command history (type to filter, Ctrl+R for older, Enter run, Esc edit)",
        "  Tab             Accept the top autocomplete (/command, @file, /skill, /resume)",
        "  @<file>         Reference a workspace file (preview shows relative; inserts absolute path)",
        "  Shift+Tab       Cycle reasoning effort (low/med/high)",
        "",
        "CLI Usage",
        "  mux-swarm \"<goal>\"",
        "  mux-swarm <goal.txt>",
        "  mux-swarm --goal \"<goal>\"",
        "  mux-swarm --goal <goal.txt>",
        "",
        "  Continuous mode:",
        "  mux-swarm --continuous --goal \"<goal>\" --goal-id my-run",
        "  mux-swarm --continuous --goal task.txt --goal-id overnight --min-delay 600",
        "",
        "  Parallel mode:",
        "  mux-swarm --parallel --goal \"<goal>\"",
        "  mux-swarm --parallel --continuous --goal \"<goal>\" --goal-id batch-run",
        "",
        "  Ex:",
        @"  mux-swarm --continuous --goal-id overnight-research --goal C:\goals\research.txt --min-delay 600 --persist-interval 120 --watchdog --docker-exec true --stdio",
        "",
        "CLI Flags",
        "  --goal <text|file>         Explicit goal",
        "  --continuous               Continuous autonomous mode",
        "  --parallel                 Use parallel swarm (concurrent batch dispatch) instead of sequential",
        "  --max-parallelism <n>      Max concurrent agent tasks in parallel mode (default 4)",
        "  --agent <name>             Run in single-agent mode with the specified agent instead of swarm",
        "  --plan                     Enable plan mode, agents confirm before executing (orchestrator and single agent only)",
        "  --ultra / --ultraplan      Maximum-reasoning mode (plan + auto sub-agents per config)",
        "  --giga                     Dynamic team/workflow orchestration mode (parity with /giga)",
        "  --sub / --subagents        Enable single-agent delegation to sub-agents",
        "  --psub / --parasubagents   Enable parallel sub-agent delegation",
        "  --verbose                  Verbose MCP / init logging",
        "  --swarm                    Boot straight into sequential swarm mode",
        "  --pswarm                   Boot straight into parallel swarm mode",
        "  --stateless                Boot straight into a stateless single-agent session",
        "  --teams                    Boot straight into teams mode",
        "  --agent-mode               Boot straight into a single-agent session (pair with --agent <name>)",
        "  --workflow <file>          Run deterministic and replayable workflows with control of the entire mux-swarm runtime",
        "  --provider <name>          Set the active LLM provider on launch (e.g. --provider ollama)",
        "  --workspace <path>         Set the @-file workspace root (defaults to CWD; point at your real project dir)",
        "  --goal-id <id>             Attach goal/session id",
        "  --min-delay <secs>         Min delay between loops (default 300)",
        "  --persist-interval <s>     Persist session every N seconds",
        "  --session-retention <n>    Keep last N sessions (default 10)",
        "  --stdio                    Machine-readable output (no ANSI)",
        "  --acp                      Run as a Zed ACP (Agent Client Protocol) server over stdio",
        "  --classic                  Force the classic line renderer (opt out of the live TUI default)",
        "  --tui                      Force the live full-screen TUI renderer (capable terminals only)",
        "  --delimiter <str>          Set multi-line input delimiter (e.g. --delimiter ---)",
        "  --watchdog                 Enable external watchdog (auto-restart on crash)",
        "  --serve <port>             Start embedded web UI (default 6723)",
        "  --daemon                   Start daemon mode (file watch, cron, status triggers from config.json)",
        "  --register                 Register mux-swarm as an OS service (survives reboots)",
        "  --remove                   Unregister mux-swarm OS service",
        "  --mcp-strict <true|false>  Require all MCPs (default true)",
        "  --docker-exec <true|false> Route exec via docker skills",
        "  --cfg <path>               Override Config.json path for scoped instance",
        "  --swarmcfg <path>          Override Swarm.json path for scoped instance",
        "  --report <session-id>      Generate audit report(s) and exit, if no session id is passed reports for all saved sessions are generated",
        "",
        "Startup Args",
        "  Persist any of the above flags to run automatically every launch with /startargs <args>",
        "  (e.g. /startargs --agent CodeAgent --giga). Stored in config.startupArgs; clear with /startargs clear.");
}