namespace MuxSwarm.Utils;

public struct Help
{
    public static readonly string HelpText = string.Join("\n",
        "Mux-Swarm — A Configurable, CLI-First Agent Swarm Runtime & Operating Environment",
        "",
        "Slash Commands",
        "  /swarm          Launch interactive multi agent swarm loop",
        "  /pswarm         Launch parallel swarm - concurrent batch dispatch for independent tasks",
        "  /agent          Launch interactive single agent loop",
        "  /onboard        Create or update your operator profile (BRAIN.md + MEMORY.md)",
        "  /stateless      Stateless single agent loop, ideal for one-off tasks",
        "  /subagents      (/sub shorthand) Enable sub-agent delegation in standard single agent loop for one-off specialist tasks",
        "  /parasubagents  (/psub shorthand) Enable parallel sub-agent delegation in standard single agent loop for one-off specialist tasks",
        "  /addcontext     Allows configuration of what context each agent is injected with (supports custom overrides)",
        "  /plan           Toggle plan mode, agents present a plan and ask for approval before executing",
        "  /classic        Switch to the classic line-by-line renderer (opt out of the live TUI)",
        "  /tui            Switch to the live full-screen TUI renderer (capable terminals only)",
        "  /verbose        Toggle TUI tool output between compact (collapsed) and full panels",
        "  /subagentview   (/sav) Toggle delegated sub-agent output between collapsed (one expandable line) and inline streaming",
        "  /continuous     Toggles continued autonomous execution on and off (shorthand /cont)",
        "  /workflow       <file> Run deterministic and replayable workflows with control of the entire mux-swarm runtime",
        "  /resume         Resume a previous single-agent session (swarm uses memory layers for continuity)",
        "  /compact        Compact current session context (applies to single agent loops only)",
        "  /maxp           Maximum number of agents that can be running in parallel. (Default 4)",
        "  /model          View current models set for your swarm",
        "  /setmodel       Change the model for any agent, orchestrator, or compaction agent in your swarm config",
        "  /swap           Swap the active agent for single-agent mode",
        "  /newagent       Guided wizard to create a swarm agent (name, MCP servers, model, prompt via helper agent or template)",
        "  /config         Show ALL configuration settings (console, ultra, serve, docker) - every key is /set-editable",
        "  /set            Edit any config key: /set <key> <value> (e.g. /set ultra.thinkingBudget 20000). Bare /set opens a picker",
        "  /provider       View or switch the active LLM provider",
        "  /limits         Display current execution limits for orchestration and agents",
        "  /tools          List available MCP tools across enabled servers",
        "  /skills         List available local skills",
        "  /memory         View knowledge graph",
        "  /sessions       List all saved sessions with type and agent count",
        "  /dockerexec     Toggle Docker execution mode",
        "  /delimiter      Toggle multi-line input delimiter",
        "  /dbg            Enable tool call output (applies to stdio mode only)",
        "  /nodbg          Disable tool call output (applies to stdio mode only)",
        "  /setup          Run initial setup / reconfigure",
        "  /reloadskills   Refresh skills directory for any mid process changes",
        "  /refresh        Perform a full Mux system refresh by refreshing config, re-initializing MCP servers and re-loading skills",
        "  /report         Generate full session audit reports, tool calls, delegations, artifacts, and outcomes",
        "  /report <id>    Audit a specific session by timestamp",
        "  /clear          Clear screen",
        "  /status         View current system status: provider, models, tools, skills, and sessions",
        "  /exit           Exit Mux-Swarm",
        "",
        "Input & Editing (live TUI)",
        "  Enter           Submit the current message",
        "  Alt+Enter       Insert a newline (multi-line compose) without submitting",
        "  Ctrl+J          Insert a newline (alias for Alt+Enter on terminals that can\u2019t signal it)",
        "  /delimiter      Alternative multi-line mode: type a delimiter line to send a pasted block",
        "  Esc             Empty prompt: open transcript view; with text: enter vim Normal mode",
        "  Ctrl+E          Expand the most recent large/collapsed tool result in place",
        "  Tab             Accept the top autocomplete (/command, @file, /skill, /resume)",
        "  @<file>         Reference a workspace file (preview shows relative; inserts absolute path)",
        "  Shift+Tab       Cycle reasoning effort (low/med/high)",
        "",
        "CLI Usage",
        "  mux-swarm \"<goal>\"",
        "  mux-swarm <goal.txt>",
        "  mux-swarm --goal \"<goal>\"",
        "  mux-swarm --goal <goal.txt>",
        "",
        "  Continuous mode:",
        "  mux-swarm --continuous --goal \"<goal>\" --goal-id my-run",
        "  mux-swarm --continuous --goal task.txt --goal-id overnight --min-delay 600",
        "",
        "  Parallel mode:",
        "  mux-swarm --parallel --goal \"<goal>\"",
        "  mux-swarm --parallel --continuous --goal \"<goal>\" --goal-id batch-run",
        "",
        "  Ex:",
        @"  mux-swarm --continuous --goal-id overnight-research --goal C:\goals\research.txt --min-delay 600 --persist-interval 120 --watchdog --docker-exec true --stdio",
        "",
        "CLI Flags",
        "  --goal <text|file>         Explicit goal",
        "  --continuous               Continuous autonomous mode",
        "  --parallel                 Use parallel swarm (concurrent batch dispatch) instead of sequential",
        "  --max-parallelism <n>      Max concurrent agent tasks in parallel mode (default 4)",
        "  --agent <name>             Run in single-agent mode with the specified agent instead of swarm",
        "  --plan                     Enable plan mode, agents confirm before executing (orchestrator and single agent only)",
        "  --workflow <file>          Run deterministic and replayable workflows with control of the entire mux-swarm runtime",
        "  --provider <name>          Set the active LLM provider on launch (e.g. --provider ollama)",
        "  --goal-id <id>             Attach goal/session id",
        "  --min-delay <secs>         Min delay between loops (default 300)",
        "  --persist-interval <s>     Persist session every N seconds",
        "  --session-retention <n>    Keep last N sessions (default 10)",
        "  --stdio                    Machine-readable output (no ANSI)",
        "  --classic                  Force the classic line renderer (opt out of the live TUI default)",
        "  --tui                      Force the live full-screen TUI renderer (capable terminals only)",
        "  --delimiter <str>          Set multi-line input delimiter (e.g. --delimiter ---)",
        "  --watchdog                 Enable external watchdog (auto-restart on crash)",
        "  --serve <port>             Start embedded web UI (default 6723)",
        "  --daemon                   Start daemon mode (file watch, cron, status triggers from config.json)",
        "  --register                 Register mux-swarm as an OS service (survives reboots)",
        "  --remove                   Unregister mux-swarm OS service",
        "  --mcp-strict <true|false>  Require all MCPs (default true)",
        "  --docker-exec <true|false> Route exec via docker skills",
        "  --cfg <path>               Override Config.json path for scoped instance",
        "  --swarmcfg <path>          Override Swarm.json path for scoped instance",
        "  --report <session-id>      Generate audit report(s) and exit, if no session id is passed reports for all saved sessions are generated");
}